name: Deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to be deployed
        default: qa
        options:
          - qa
          - preprod
          - prod
      development_version:
        description: Development version bundle
        required: true
      release_version:
        description: Release version bundle
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        shell: bash
        run: |
          echo "${{ github.event.inputs.environment }}"
          echo "${{ github.event.inputs.development_version }}"
          echo "${{ github.event.inputs.release_version }}"
